version: "3.8"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: mzegarra/remote-host
    build:
      context: centos8
    networks:
      - net      
networks:
  net: